app:
  name: ditto
  host: 0.0.0.0
  port: 6106
  version: 1
  ctxTimeout: 30s
  baseURL: http://localhost:6106
  templatePath: ["./resources/views/layout/*.gohtml","./resources/views/modal/*.gohtml","./resources/views/pages/*.gohtml"]
  staticPath: "./resources/public/assets"
database:
  host: alexandria.allobank.local
  port: 3306
  user: root
  pass: root
  databaseName: ditto
  charset: utf8mb4
  debugLog: true
  pool:
    maxConnLifetime: 1m
    maxIdleConn: 5
    maxOpenConn: 50
