services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonclay
      MYSQL_USER: user
      MYSQL_PASSWORD: root@321
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    command: redis-server --appendonly yes

networks:
  backend:
    external: true

volumes:
  data:
