/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/Layout/AppLayout.vue')['default']
    First: typeof import('./src/components/Layout/first.vue')['default']
    MenuItem: typeof import('./src/components/Layout/MenuItem.vue')['default']
    MenuSection: typeof import('./src/components/Layout/MenuSection.vue')['default']
    MobileHeader: typeof import('./src/components/Layout/MobileHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    SidebarHeader: typeof import('./src/components/Layout/SidebarHeader.vue')['default']
    TopHeader: typeof import('./src/components/Layout/TopHeader.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
